language: scala

jdk:
- oraclejdk8
- openjdk11

scala:
- 2.11.12
- 2.12.8
- 2.13.0

script:
- sbt ++$TRAVIS_SCALA_VERSION! test

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
